# Generated by Django 6.0.5 on 2026-06-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'posts', 'verbose_name_plural': 'posts'},
        ),
    ]
