# Generated by Django 6.0.5 on 2026-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_posts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JambForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('jamb_number', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
