# Generated by Django 6.0.5 on 2026-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_jambform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Books')),
            ],
        ),
    ]
