# Generated by Django 6.0.5 on 2026-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
